[toolchain]
package_manager = "pnpm"
anchor_version = "1.2.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
strategy_registry = "3twgH9P4Knu51EqMZb5Fx2CSX1vUkw5Da4GYSUjiNzNs"

[programs.devnet]
strategy_registry = "3twgH9P4Knu51EqMZb5Fx2CSX1vUkw5Da4GYSUjiNzNs"

[programs.mainnet]
strategy_registry = "3twgH9P4Knu51EqMZb5Fx2CSX1vUkw5Da4GYSUjiNzNs"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec mocha --require tsx \"programs/strategy-registry/tests/**/*.ts\""
